version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=MagicWord
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - xpack.security.enabled=true
      - xpack.ml.enabled=true
      - xpack.watcher.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=MagicWord
    ports:
     - 5601:5601
    networks:
     - esnet
    depends_on:
     - elasticsearch

  app-search:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_ENV: local
    environment:
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "4010:4010"
    networks:
      - esnet

networks:
  esnet:
