service: serverless-sample

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  environment:
    NODE_ENV: ${self:custom.stage}
  region: us-east-1

functions:
  isMutant:
    handler: lib/handler.isMutant
    events:
      - http:
          path: mutant
          method: post

custom:
  stage: ${opt:stage, 'local'}
  serverless-offline:
    port: 4010
